#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAnimateRadioGroup.Resource", IsApplication=true)]

namespace XamarinAnimateRadioGroup
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int Amarela = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int AmareloFlorescente = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int AmareloLimaLimao = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int Azul = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Branca = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Laranja = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int Marron = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int Preto = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Verde = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int Vermelho = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int colorAccent = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int colorPrimaryDark = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_circulo_amarela = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_circulo_amarelo_florescente = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_circulo_amarelo_lima_limao = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_circulo_azul = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_circulo_branco = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_circulo_laranja = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_circulo_marron = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_circulo_preto = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_circulo_verde = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_circulo_vermelho = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int toggle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int toggle_checked = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int toggle_checked_unchecked = 2130837516;
			
			// aapt resource value: 0x7f02000f
			public const int toggle_checked_unchecked_1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int toggle_checked_unchecked_2 = 2130837520;
			
			// aapt resource value: 0x7f02000d
			public const int toggle_unchecked = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int toggle_unchecked_checked = 2130837518;
			
			// aapt resource value: 0x7f020011
			public const int toggle_unchecked_checked_1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int toggle_unchecked_checked_2 = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int CorImageViewRadioGroup = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int Scroll_RadioGroup = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int @checked = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int rd_Preto = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int rd_amarela = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int rd_amareloFlorescente = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int rd_amareloLimaLimao = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int rd_azul = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int rd_branca = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int rd_marron = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int rd_verde = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int rd_vermelho = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int rgRadioGroup = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int @unchecked = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
